config/routes.rb
Habitapp::Application.routes.draw do

  resources :users

  resources :habits

  root :to => "pages#landing"
    
  match '/auth/twitter/callback', to: 'sessions#create'
  match '/auth/twitter', :as => :twitter_auth
  
  match "/myhabits" => "habits#index", :as => :my_habits
  match "/signout" => "sessions#destroy"

end

app/models/datapoint.rb
class Datapoint < ActiveRecord::Base
  
  belongs_to :datapointgroup
  
end

app/models/datapointgroup.rb
class Datapointgroup < ActiveRecord::Base
  
  has_many :datapoints
  belongs_to :habit
  
end

app/models/habit.rb
class Habit < ActiveRecord::Base
  
  belongs_to :user
  has_many :reasons
  has_many :datapointgroups
  has_many :referees, :through => :habit_referee
  
end

app/models/habit_referee.rb
class HabitReferee < ActiveRecord::Base
  
  belongs_to :habit
  belongs_to :referee
  
end

app/models/reason.rb
class Reason < ActiveRecord::Base
  
  belongs_to :habit
  
end

app/models/referee.rb
class Referee < ActiveRecord::Base
  
  has_many :habits, :through => :habit_referee
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :habits
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.twitter_handle = auth["info"]["nickname"]

    end
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :logged_in

  private

  def logged_in
    if session[:user_id]
      @current_user ||= (User.find(session[:user_id]))
    else
      redirect_to :root
    end
  end
  
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  
  before_filter :logged_in
  
  # GET /habits
  # GET /habits.json
  def index
    @habits = @current_user.habits

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @habits }
    end
  end

  # GET /habits/1
  # GET /habits/1.json
  def show
    @habit = Habit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @habit }
    end
  end

  # GET /habits/new
  # GET /habits/new.json
  def new
    @habit = Habit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @habit }
    end
  end

  # GET /habits/1/edit
  def edit
    @habit = Habit.find(params[:id])
  end

  # POST /habits
  # POST /habits.json
  def create
    
    @user = @current_user
    @habit = @user.habits.new(params[:habit])

    respond_to do |format|
      if @habit.save
        format.html { redirect_to @habit, notice: 'Habit was successfully created.' }
        format.json { render json: @habit, status: :created, location: @habit }
      else
        format.html { render action: "new" }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /habits/1
  # PUT /habits/1.json
  def update
    @habit = Habit.find(params[:id])

    respond_to do |format|
      if @habit.update_attributes(params[:habit])
        format.html { redirect_to @habit, notice: 'Habit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habits/1
  # DELETE /habits/1.json
  def destroy
    @habit = Habit.find(params[:id])
    @habit.destroy

    respond_to do |format|
      format.html { redirect_to habits_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def landing
    render :layout => 'landing'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to :my_habits, :notice => "Signed in!"
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to :root, :notice => "Signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/habits/_form.html.haml
= form_for @habit do |f|
  -if @habit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@habit.errors.count, "error")} prohibited this habit from being saved:"
      %ul
        - @habit.errors.full_messages.each do |msg|
          %li= msg

  .field
    /= f.label :makebreak
    = f.check_box :makebreak
  .field
    I want to break the habit of
    = f.text_field :title
    because
    = f.text_field :description
  .field
    I will track my progress every
    = f.number_field :frequency
    day(s),
    for
    = f.number_field :duration
    days.
  .field
    If I relapse, the consequence will be
    = f.text_field :consequence
  .field
    = f.number_field :referee_id
    will act as my referee and hold me accountable to this commitment. Their email address is
  .actions
    = f.submit 'Save'
    
    /MAKE A HABIT
    /I want to make a habit of __[working out 3 days a week]__ because __[I want to improve my health]__.
    /I will track my progress every [day][week][month] for __[60]__ days/weeks/months.
    /_[Friend's name here]_ will act as my referee and hold me accountable to this commitment. Their email is __[friend@email.com__]
    /If I fail to maintain this habit, the consequences will be __[no coffee for a week]__.
    
    /BREAK A HABIT
    /I want to break the habit of __[smoking]__ because __[I want to live longer]__.
    /I will track my progress every [day][week][month] for __[60]__ days/weeks/months..
    /_[Friend's name here]_ will act as my referee and hold me accountable to this commitment. Their email is __[friend@email.com__].
    /If I relapse, the consequences will be __[I must give $100 to the KKK]__.

app/views/habits/edit.html.haml
%h1 Editing habit

= render 'form'

= link_to 'Show', @habit
\|
= link_to 'Back', habits_path

app/views/habits/index.html.haml
%h1
  = "@#{@current_user.twitter_handle}'s habits"

%table
  %tr
    %th Makebreak
    %th Title
    %th Description
    %th Frequency
    %th Duration
    %th Consequence
    %th User
    %th Referee
    %th
    %th
    %th

  - @habits.each do |habit|
    %tr
      %td= habit.makebreak
      %td= habit.title
      %td= habit.description
      %td= habit.frequency
      %td= habit.duration
      %td= habit.consequence
      %td= habit.user_id
      %td= habit.referee_id
      %td= link_to 'Show', habit
      %td= link_to 'Edit', edit_habit_path(habit)
      %td= link_to 'Destroy', habit, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Habit', new_habit_path

app/views/habits/new.html.haml
%h1 New habit
/%h4 All fields required

= render 'form'

= link_to 'Back', habits_path

app/views/habits/show.html.haml
%p#notice= notice

/ %p
/   %b Makebreak:
/   = @habit.makebreak
%h1 
  Quit
  = @habit.title
#graph
  /= image_tag("/assets/loading.gif", :id => "loadingimage", :style => "margin:100px 300px;") 
/ %p
/   %b Description:
/   = @habit.description
/ %p
/   %b Frequency:
/   = @habit.frequency
/ %p
/   %b Duration:
/   = @habit.duration
/ %p
/   %b Consequence:
/   = @habit.consequence
/ %p
/   %b User:
/   = @habit.user_id
/ %p
/   %b Referee:
/   = @habit.referee_id

= link_to 'Edit', edit_habit_path(@habit)
\|
= link_to 'Back', habits_path

:javascript
  window.onload = function(){graph([0,1,2,3,4,5,6,0,1,2,3,4,5,0,1,2,3,4,5,6,7,8,9])}

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Habitapp"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href=my_habits_url) Habitapp
          .container.nav-collapse
            %ul.nav

              %li= link_to "My Habits", :my_habits
              %li= link_to "Log Out", signout_path

    .container-fluid

      .row-fluid
        / .span3
        /   .well.sidebar-nav
        /     %ul.nav.nav-list
        /       %li.nav-header Sidebar
        /       %li= link_to "Link 1", "/path1"
        /       %li= link_to "Link 2", "/path2"
        /       %li= link_to "Link 3", "/path3"
        .span9
          = yield
    
      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"


app/views/layouts/landing.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Habit"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    = link_to "Sign in", :twitter_auth
    #landing_container
      I want to
      #pickone
        (pick one)
      #landing_button_container
        #make_button
          MAKE
        #break_button
          BREAK
      #clear
        a habit.

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"


app/views/pages/landing.html.haml
%h1 Pages#landing
%p Find me in app/views/pages/landing.html.haml

app/views/users/_form.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email_address
    = f.text_field :email_address
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :provider
    = f.text_field :provider
  .field
    = f.label :uid
    = f.text_field :uid
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Email address
    %th First name
    %th Last name
    %th Provider
    %th Uid
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.email_address
      %td= user.first_name
      %td= user.last_name
      %td= user.provider
      %td= user.uid
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Email address:
  = @user.email_address
%p
  %b First name:
  = @user.first_name
%p
  %b Last name:
  = @user.last_name
%p
  %b Provider:
  = @user.provider
%p
  %b Uid:
  = @user.uid

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path